basePath: '{{.BasePath}}'
definitions:
  controller.Message:
    properties:
      data:
        type: object
      message:
        type: string
      status:
        type: integer
    type: object
  model.DianWorkWrapper:
    properties:
      construction_company:
        example: 飞燕工程队
        type: string
      desc:
        example: 包吃包住
        type: string
      final_treatment:
        items:
          type: string
        type: array
      location:
        example: 湖北省襄阳市
        type: string
      location_info:
        $ref: '#/definitions/model.LocationInfoWrapper'
        type: object
      max_wage:
        example: "200"
        type: string
      min_wage:
        example: "100"
        type: string
      need:
        example: 钢筋工
        type: string
      project_name:
        example: 主楼建造
        type: string
      required_people:
        example: "11"
        type: string
      settlement:
        example: 月薪
        type: string
      type:
        example: 消防
        type: string
      user_id:
        example: 1
        type: integer
    type: object
  model.GroupRequest:
    properties:
      group_name:
        type: string
      owner_id:
        type: integer
    type: object
  model.LocationInfoWrapper:
    properties:
      addr:
        example: 湖北省襄阳市樊城区武商广场店对面人民公园
        type: string
      latitude:
        example: "32.04278"
        type: string
      longitude:
        example: "112.15519"
        type: string
      title:
        example: 人民广场
        type: string
    type: object
  model.WxUserWrapper:
    properties:
      hometown:
        example: 江苏
        type: string
      nick_name:
        example: 飞燕一号
        type: string
      phone:
        example: "133333"
        type: string
      real_name:
        example: 张三
        type: string
      sex:
        example: 男
        type: string
      wx_id:
        example: jajsjasja11233
        type: string
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: YANFEI API
  version: 0.0.1
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: 测试服务器是否在线
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Message'
            type: object
      summary: PING-PONG
      tags:
      - miscellaneous
  /wx/group/in_group:
    get:
      consumes:
      - application/json
      description: 查询自己参与的班组，包括自己创建和加入的
      parameters:
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Message'
            type: object
      summary: 查询自己参与的班组
      tags:
      - wx
  /wx/group/join_group:
    get:
      consumes:
      - application/json
      description: 加入群组
      parameters:
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: string
      - description: 群组入群口令
        in: query
        name: group_key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Message'
            type: object
      summary: 加入群组
      tags:
      - wx
  /wx/group/new_group:
    post:
      consumes:
      - application/json
      description: 创建新群组
      parameters:
      - description: create a new group
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.GroupRequest'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Message'
            type: object
      summary: 创建新群组
      tags:
      - wx
  /wx/info/project_types:
    get:
      description: 获取所有工程类别
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Message'
            type: object
      summary: 获取所有工程类别
      tags:
      - wx
  /wx/info/worker_types:
    get:
      description: 获取所有工种
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Message'
            type: object
      summary: 获取所有工种
      tags:
      - wx
  /wx/user/new_user:
    post:
      consumes:
      - application/json
      description: 小程序端新添用户
      parameters:
      - description: create a new user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.WxUserWrapper'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Message'
            type: object
      summary: 小程序端新添用户
      tags:
      - wx
      - user
  /wx/work/publish:
    post:
      consumes:
      - application/json
      description: 发布工作
      parameters:
      - description: 工种 0(点工),1(包工),2(突击队) 必填
        in: query
        name: work_type
        required: true
        type: string
      - description: 点工招聘
        in: body
        name: 点工示例数据
        schema:
          $ref: '#/definitions/model.DianWorkWrapper'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Message'
            type: object
      summary: 发布工作
      tags:
      - wx
  /wx/work/search:
    get:
      description: 搜索工作，需要某个筛选参数就加上，否则可以不加；按发布时间降序排序
      parameters:
      - description: 二级位置信息 选填
        in: query
        name: location
        type: string
      - description: 所需工种 选填
        in: query
        name: need
        type: string
      - description: 工程类别 选填
        in: query
        name: type
        type: string
      - description: 工作类别 选填0只返回点工和包工，1只返回突击队，默认为0
        in: query
        name: work_type
        type: string
      - description: 页码，从1开始 必填
        in: query
        name: page
        required: true
        type: string
      - description: 每页记录数 必填
        in: query
        name: limit
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Message'
            type: object
      summary: 搜索工作
      tags:
      - wx
swagger: "2.0"
