basePath: '{{.BasePath}}'
definitions:
  controller.Message:
    properties:
      data:
        type: object
      message:
        type: string
      status:
        type: integer
    type: object
  model.BaoWorkReq:
    properties:
      construction_company:
        example: 飞燕工程队
        type: string
      desc:
        example: 包吃包住
        type: string
      final_treatment:
        items:
          type: string
        type: array
      location:
        example: 湖北省襄阳市
        type: string
      location_info:
        $ref: '#/definitions/model.LocationInfoReq'
        type: object
      need:
        example: 钢筋工
        type: string
      project_name:
        example: 主楼建造
        type: string
      scale:
        example: 大
        type: string
      totle_price:
        example: "300"
        type: string
      type:
        example: 消防
        type: string
      unit:
        example: 元/平方米
        type: string
      unit_price:
        example: "2"
        type: string
    type: object
  model.DianWorkReq:
    properties:
      construction_company:
        example: 飞燕工程队
        type: string
      desc:
        example: 包吃包住
        type: string
      final_treatment:
        items:
          type: string
        type: array
      location:
        example: 湖北省襄阳市
        type: string
      location_info:
        $ref: '#/definitions/model.LocationInfoReq'
        type: object
      max_wage:
        example: "200"
        type: string
      min_wage:
        example: "100"
        type: string
      need:
        example: 钢筋工
        type: string
      project_name:
        example: 主楼建造
        type: string
      required_people:
        example: "11"
        type: string
      settlement:
        example: 月薪
        type: string
      type:
        example: 消防
        type: string
    type: object
  model.GroupRequest:
    properties:
      group_name:
        type: string
    type: object
  model.HourRecordRequest:
    properties:
      extra_work_hours:
        example: 1
        type: number
      group_id:
        example: 1
        type: integer
      record_date:
        example: "2019-05-19"
        type: string
      work_hours:
        example: 1.5
        type: number
      worker_id:
        example: 2
        type: integer
    type: object
  model.ItemRecordRequest:
    properties:
      group_id:
        example: 1
        type: integer
      quantity:
        example: 1
        type: number
      record_date:
        example: "2019-05-19"
        type: string
      subitem:
        example: 刷墙
        type: string
      worker_id:
        example: 2
        type: integer
    type: object
  model.LocationInfoReq:
    properties:
      addr:
        example: 湖北省襄阳市樊城区武商广场店对面人民公园
        type: string
      latitude:
        example: "32.04278"
        type: string
      longitude:
        example: "112.15519"
        type: string
      title:
        example: 人民广场
        type: string
    type: object
  model.TujiWorkReq:
    properties:
      construction_company:
        example: 飞燕工程队
        type: string
      desc:
        example: 包吃包住
        type: string
      final_treatment:
        items:
          type: string
        type: array
      location:
        example: 湖北省襄阳市
        type: string
      location_info:
        $ref: '#/definitions/model.LocationInfoReq'
        type: object
      money:
        example: 80
        type: integer
      need:
        example: 钢筋工
        type: string
      project_name:
        example: 主楼建造
        type: string
      required_people:
        example: 12
        type: integer
      type:
        example: 消防
        type: string
      work_date:
        example: "2019-05-12"
        type: string
      work_days:
        example: 10
        type: integer
      work_time:
        example: "8"
        type: string
    type: object
  model.WxUserInfo:
    properties:
      hometown:
        example: 江苏
        type: string
      nick_name:
        example: 飞燕一号
        type: string
      phone:
        example: "133333"
        type: string
      real_name:
        example: 张三
        type: string
      sex:
        example: 男
        type: string
      user_id:
        type: integer
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: YANFEI API
  version: 0.0.1
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: 测试服务器是否在线
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Message'
            type: object
      summary: PING-PONG
      tags:
      - 测试
  /wx/group/delete_member:
    get:
      consumes:
      - application/json
      description: 删除班组中某个成员
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 班组id
        in: query
        name: group_id
        required: true
        type: integer
      - description: 删除用户id
        in: query
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Message'
            type: object
      summary: 删除班组中某个成员
      tags:
      - 班组相关
  /wx/group/group_member:
    get:
      consumes:
      - application/json
      description: 获取班组所有成员
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 班组id
        in: query
        name: group_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Message'
            type: object
      summary: 获取班组所有成员
      tags:
      - 班组相关
  /wx/group/in_group:
    get:
      consumes:
      - application/json
      description: 查询自己参与的班组，包括自己创建和加入的
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Message'
            type: object
      summary: 查询自己参与的班组
      tags:
      - 班组相关
  /wx/group/join_group:
    get:
      consumes:
      - application/json
      description: 加入班组
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 群组入群口令
        in: query
        name: group_key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Message'
            type: object
      summary: 加入班组
      tags:
      - 班组相关
  /wx/group/new_group:
    post:
      consumes:
      - application/json
      description: 创建新班组
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 创建新班组
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.GroupRequest'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Message'
            type: object
      summary: 创建新班组
      tags:
      - 班组相关
  /wx/info/project_types:
    get:
      description: 获取所有工程类别
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Message'
            type: object
      summary: 获取所有工程类别
      tags:
      - 各种类型信息
  /wx/info/worker_types:
    get:
      description: 获取所有工种
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Message'
            type: object
      summary: 获取所有工种
      tags:
      - 各种类型信息
  /wx/record/add_hour_record:
    post:
      description: 添加工时记录
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 工时记录数据
        in: body
        name: 工时记录数据
        required: true
        schema:
          $ref: '#/definitions/model.HourRecordRequest'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Message'
            type: object
      summary: 添加工时记录
      tags:
      - 工作记录相关
  /wx/record/add_item_record:
    post:
      description: 添加分项记录
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 分项记录数据
        in: body
        name: 分项记录数据
        required: true
        schema:
          $ref: '#/definitions/model.ItemRecordRequest'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Message'
            type: object
      summary: 添加分项记录
      tags:
      - 工作记录相关
  /wx/record/check_recorded:
    get:
      description: 检查某日是否记录
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 班组id
        in: query
        name: group_id
        required: true
        type: integer
      - description: 工人id
        in: query
        name: worker_id
        required: true
        type: integer
      - description: 日期
        in: query
        name: date
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Message'
            type: object
      summary: 检查某日是否记录
      tags:
      - 工作记录相关
  /wx/user/get_user_info:
    get:
      consumes:
      - application/json
      description: 获取用户信息
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Message'
            type: object
      summary: 获取用户信息
      tags:
      - 用户相关
  /wx/user/login:
    get:
      consumes:
      - application/json
      description: 小程序用户登录
      parameters:
      - description: 登录码
        in: query
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Message'
            type: object
      summary: 小程序用户登录
      tags:
      - 用户相关
  /wx/user/update_user_info:
    post:
      consumes:
      - application/json
      description: 更新用户信息
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 用户个人信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.WxUserInfo'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Message'
            type: object
      summary: 更新用户信息
      tags:
      - 用户相关
  /wx/work/publish_bao:
    post:
      consumes:
      - application/json
      description: 发布包工工作
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 包工招聘数据
        in: body
        name: bao_work
        required: true
        schema:
          $ref: '#/definitions/model.BaoWorkReq'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Message'
            type: object
      summary: 发布包工工作
      tags:
      - 工作相关
  /wx/work/publish_dian:
    post:
      consumes:
      - application/json
      description: 发布点工工作
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 点工招聘数据
        in: body
        name: dian_work
        required: true
        schema:
          $ref: '#/definitions/model.DianWorkReq'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Message'
            type: object
      summary: 发布点工工作
      tags:
      - 工作相关
  /wx/work/publish_tuji:
    post:
      consumes:
      - application/json
      description: 发布突击队工作
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 突击队招聘数据
        in: body
        name: tuji_work
        required: true
        schema:
          $ref: '#/definitions/model.TujiWorkReq'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Message'
            type: object
      summary: 发布突击队工作
      tags:
      - 工作相关
  /wx/work/search:
    get:
      description: 搜索工作，需要某个筛选参数就加上，否则可以不加；按发布时间降序排序
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 二级位置信息 选填
        in: query
        name: location
        type: string
      - description: 所需工种 选填
        in: query
        name: need
        type: string
      - description: 工程类别 选填
        in: query
        name: type
        type: string
      - description: 工作类别 选填0只返回点工和包工，1只返回突击队，默认为0
        in: query
        name: work_type
        type: integer
      - description: 页码，从1开始 必填
        in: query
        name: page
        required: true
        type: integer
      - description: 每页记录数 必填
        in: query
        name: limit
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Message'
            type: object
      summary: 搜索工作
      tags:
      - 工作相关
swagger: "2.0"
